domain_root: "platform.internal"
# global service
domain_global_infra: "infra.{{ domain_root }}"

timezone: Europe/Kyiv

dns_domain: platform.internal

dns_search:
  - platform.internal

dns_servers:
  - 10.50.60.53

ntp_servers:
  - 10.50.60.56

inet_proxy:
  http_proxy: http://10.50.60.59:5555
  https_proxy: http://10.50.60.59:5555
  no_proxy:
    - localhost
    - 127.0.0.1
    - .platform.internal
    - 192.168.0.0/16
    - 10.0.0.0/8
