env_tier: "prod"
domain_root: "platform.internal"

# global service
domain_global_infra: "infra.{{ domain_root }}"

# Use internal Nexus repositories for this host
repo_use_internal_repos: false

# Deploy Nexus Repository on this host
repo_nexus_enabled: false

common_upgrade_packages: false

timezone: Europe/Kyiv

dns_domain: platform.internal

dns_search:
  - platform.internal

dns_servers:
  - 10.50.60.53

ntp_servers:
  - 10.50.60.56

proxy_enabled: false

inet_proxy:
  http_proxy: http://10.50.60.59:5555
  https_proxy: http://10.50.60.59:5555
  no_proxy:
    - localhost
    - 127.0.0.1
    - .platform.internal
    - 192.168.0.0/16
    - 10.0.0.0/8

domain_env_root: "{{ env_tier }}.{{ domain_root }}" # prod.platform.internal
domain_infra: "infra.{{ domain_env_root }}" # infra.prod.platform.internal
domain_k8s: "k8s.{{ domain_env_root }}" # k8s.prod.platform.internal
domain_apps: "apps.{{ domain_env_root }}" # apps.prod.platform.internal

repo_fqdn: repo-01.infra.platform.internal

repo_rocky_baseos_url: "http://{{ repo_fqdn }}:8081/repository/rocky-9-baseos/"
repo_rocky_appstream_url: "http://{{ repo_fqdn }}:8081/repository/rocky-9-appstream/"

repo_rocky_local_gpg_path: "/etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-9"
