---
worker_cri_socket: "unix:///run/containerd/containerd.sock"

worker_join_timeout: 120

worker_join_token_ttl: "30m"

worker_kubelet_config: "/etc/kubernetes/kubelet.conf"

worker_kubeadm_config: "/etc/kubernetes/kubeadm-join.yaml"

kubernetes_firewall_rules:
  - proto: tcp
    from_cidr: "{{ kubernetes_control_plane_cidr }}"
    port: 4240
    comment: "Cilium health from Control Plane"

  - proto: tcp
    from_cidr: "{{ kubernetes_worker_cidr }}"
    port: 4240
    comment: "Cilium health from Workers"

  - proto: tcp
    from_cidr: "{{ kubernetes_control_plane_cidr }}"
    port: "{{ kubernetes_kubelet_port }}"
    comment: "Kubelet API from Control Plane"

kubernetes_firewall_forward_rules:
  - from_cidr: "{{ kubernetes_worker_cidr }}"
    to_cidr: "{{ cilium_native_routing_cidr }}"
    comment: "Kubernetes worker to Pod network"

  - from_cidr: "{{ cilium_native_routing_cidr }}"
    to_cidr: "{{ kubernetes_worker_cidr }}"
    comment: "Pod network to Kubernetes worker"
