---
proxy_enabled: false
repo_use_internal_repos: true
common_upgrade_packages: true

vault_cluster_name: "vault-prod"
vault_domain: "infra.platform.internal"
vault_fqdn: "{{ inventory_hostname }}.{{ vault_domain }}"

vault_yum_repo_name: "hashicorp-yum"
vault_yum_repo_url: "http://{{ repo_fqdn }}:8081/repository/{{ vault_yum_repo_name }}/"

vault_api_addr: "https://{{ inventory_hostname }}.{{ vault_domain }}:8200"
vault_cluster_addr: "https://{{ inventory_hostname }}.{{ vault_domain }}:8201"

vault_tls_ca_common_name: "Platform Vault CA"

vault_tls_controller_pki_dir: "{{ lookup('env', 'HOME') }}/.ansible/pki/vault"

vault_tls_ca_key_local: "{{ vault_tls_controller_pki_dir }}/ca.key"
vault_tls_ca_cert_local: "{{ vault_tls_controller_pki_dir }}/ca.crt"

vault_tls_enabled: true

vault_raft_enabled: true
vault_raft_cluster_name: "vault-prod"

vault_bootstrap_node: "vault-01"
