ntp_package: chrony
ntp_service: chrony
ntp_config_path: /etc/chrony/chrony.conf
ntp_driftfile: /var/lib/chrony/chrony.drift
ntp_keyfile: /etc/chrony/chrony.keys

common_packages:
  - vim
  - curl
  - wget
  - bash-completion
  - tar
  - unzip
  - dnsutils
  - net-tools
  - lsof
  - tcpdump
  - rsync
  - jq
