---
- name: DNS | Install systemd-resolved
  ansible.builtin.apt:
    name: systemd-resolved
    state: present
    update_cache: false

- name: DNS | Configure systemd-resolved
  ansible.builtin.template:
    src: debian_resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart systemd-resolved

- name: DNS | Enable and start systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    enabled: true
    state: started

- name: DNS | Configure /etc/resolv.conf
  ansible.builtin.file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: true

- name: DNS | Verify repository hostname resolution
  ansible.builtin.command:
    cmd: getent hosts repo-01.infra.platform.internal
  register: repo_dns_check
  changed_when: false
  failed_when: repo_dns_check.rc != 0
