- name: Load OS variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Configure hostname
  include_tasks: hostname.yml

- name: Configure timezone
  include_tasks: timezone.yml

- name: Configure DNS
  include_tasks: dns.yml

- name: Configure repo
  include_tasks: repo.yml
  when: repo_enabled | default(false)

- name: Configure proxy
  include_tasks: proxy.yml
  when: proxy_enabled | default(false)

- name: Upgrade OS
  include_tasks: upgrade.yml

- name: Configure NTP
  include_tasks: ntp.yml

- name: Install common packages
  include_tasks: packages.yml
