---
- name: Restart HAProxy
  ansible.builtin.systemd:
    name: "{{ haproxy_service }}"
    state: restarted

- name: Restart Keepalived
  ansible.builtin.systemd:
    name: "{{ keepalived_service }}"
    state: restarted
