ansible_user: ansible-vyos
ansible_password: "{{ vault_vyos_ansible_password }}"
ansible_connection: network_cli
ansible_network_os: vyos.vyos.vyos

# Existing interface structures...
mgmt_interface:
  name: "eth0"
  ip: "10.50.10.1/24"
  description: "Management"

vgt_vlans:
  - id: 20
    name: Infrastructure
    subnet: "10.50.20"

    router_ips:
      primary: 10.50.20.1
      secondary: 10.50.20.2

    gateway: 10.50.20.254

    dhcp:
      enabled: true
      range:
        start: 100
        stop: 199

    # dns_servers:
    #  - "10.50.10.11"
    #  - "10.50.10.12"

  - id: 30
    name: Control-Plane
    subnet: "10.50.30"

  - id: 40
    name: etcd
    subnet: "10.50.40"

  - id: 50
    name: Workers
    subnet: "10.50.50"

  - id: 60
    name: Services
    subnet: "10.50.60"

  - id: 70
    name: Monitoring
    subnet: "10.50.70"

  - id: 80
    name: Databases
    subnet: "10.50.80"

  - id: 90
    name: Storage
    subnet: "10.50.90"

  - id: 99
    name: Transit
    subnet: "10.50.99"
