- name: Give Nexus extra time to initialize web services
  ansible.builtin.pause:
    seconds: 5

- name: Configure Nexus global HTTP/HTTPS proxy
  ansible.builtin.uri:
    url: "{{ repo_nexus_api_url }}/service/rest/v1/http"
    method: PUT
    user: "{{ repo_nexus_admin_user }}"
    password: "{{ repo_nexus_admin_password }}"
    force_basic_auth: true
    headers:
      Accept: "application/json"
      Content-Type: "application/json"
    body_format: json
    body:
      nonProxyHosts: "{{ repo_nexus_proxy_non_proxy_hosts }}"
      userAgent: "{{ repo_nexus_http_user_agent }}"
      timeout: "{{ repo_nexus_http_timeout }}"
      retries: "{{ repo_nexus_http_retries }}"

      httpProxy:
        enabled: "{{ repo_nexus_http_proxy_enabled }}"
        host: "{{ repo_nexus_http_proxy_host }}"
        port: "{{ repo_nexus_http_proxy_port }}"
        authInfo:
          enabled: "{{ repo_nexus_http_proxy_auth_enabled }}"
          username: "{{ repo_nexus_http_proxy_username }}"
          password: "{{ repo_nexus_http_proxy_password }}"

      httpsProxy:
        enabled: "{{ repo_nexus_https_proxy_enabled }}"
        host: "{{ repo_nexus_https_proxy_host }}"
        port: "{{ repo_nexus_https_proxy_port }}"
        authInfo:
          enabled: "{{ repo_nexus_https_proxy_auth_enabled }}"
          username: "{{ repo_nexus_https_proxy_username }}"
          password: "{{ repo_nexus_https_proxy_password }}"

    status_code:
      - 200
      - 204
    validate_certs: false
# no_log: true
