---
- name: Pull Nexus Repository image
  community.docker.docker_image:
    name: "{{ repo_nexus_image }}"
    source: pull

- name: Start Nexus Repository container
  community.docker.docker_container:
    name: "{{ repo_nexus_container_name }}"
    image: "{{ repo_nexus_image }}"
    state: started
    restart_policy: unless-stopped

    env:
      HTTP_PROXY: "{{ inet_proxy.http_proxy }}"
      HTTPS_PROXY: "{{ inet_proxy.https_proxy }}"
      NO_PROXY: "{{ inet_proxy.no_proxy | join(',') }},{{ repo_fqdn }}"

    ports:
      - "{{ repo_nexus_bind_address }}:{{ repo_nexus_port }}:8081"
      - "{{ repo_nexus_bind_address }}:8082:8082" #for docker
      - "{{ repo_nexus_bind_address }}:8083:8083" #for k8s
      - "{{ repo_nexus_bind_address }}:8084:8084" #for quay

    volumes:
      - "{{ repo_nexus_data_path }}:/nexus-data"

    ulimits:
      - "nofile:65536:65536"
