---
- name: Configure repository server
  when: repo_nexus_enabled | bool
  become: true
  block:
    - name: Run repository prerequisites
      ansible.builtin.include_tasks:
        file: prerequisites.yml

    - name: Install Nexus Repository
      ansible.builtin.include_tasks:
        file: install.yml

    - name: Configure Nexus Repository
      ansible.builtin.include_tasks:
        file: configure.yml

    - name: Configure package repositories
      ansible.builtin.include_tasks:
        file: repositories.yml

    - name: Set Global Proxy Nexus
      ansible.builtin.include_tasks:
        file: global_proxy.yml

    - name: Verify Nexus
      ansible.builtin.include_tasks: nexus_verify.yml

    # - name: Verify repository connectivity
    #   ansible.builtin.include_tasks: nexus_repository_verify.yml
