---
- name: Configure repository server
  when: repo_enabled | bool
  block:
    - name: Run repository prerequisites
      ansible.builtin.include_tasks:
        file: prerequisites.yml

    - name: Configure Pulp
      ansible.builtin.include_tasks:
        file: pulp.yml
      environment:
        http_proxy: "{{ inet_proxy.http_proxy }}"
        https_proxy: "{{ inet_proxy.https_proxy }}"
        no_proxy: "{{ inet_proxy.no_proxy | join(',') }}"
