- name: Install repository host prerequisites
  ansible.builtin.dnf:
    name:
      - git
      - curl
      - tar
      - gzip
      - policycoreutils-python-utils
      - python3.11
      - python3-psycopg2
      #- python3.11-pip
      #- python3.11-devel
    state: present
# - name: Ensure Pulp virtualenv exists
#   ansible.builtin.pip:
#     name: pip
#     state: latest
#     virtualenv: /usr/local/lib/pulp
#     virtualenv_command: /usr/bin/python3 -m venv
#   environment:
#     http_proxy: "{{ inet_proxy.http_proxy }}"
#     https_proxy: "{{ inet_proxy.https_proxy }}"
#     no_proxy: "{{ inet_proxy.no_proxy | join(',') }}"

# - name: Check typing_extensions in Pulp virtualenv
#   ansible.builtin.command:
#     cmd: /usr/local/lib/pulp/bin/python -m pip show typing_extensions
#   register: repo_pulp_typing_extensions
#   changed_when: false
#   failed_when: false

# - name: Install typing_extensions in Pulp virtualenv
#   ansible.builtin.command:
#     cmd: /usr/local/lib/pulp/bin/python -m pip install typing_extensions
#   environment:
#     http_proxy: "{{ inet_proxy.http_proxy }}"
#     https_proxy: "{{ inet_proxy.https_proxy }}"
#     no_proxy: "{{ inet_proxy.no_proxy | join(',') }}"
#   when: repo_pulp_typing_extensions.rc != 0

# - name: Ensure Pulp user owns the virtualenv directory
#   ansible.builtin.file:
#     path: /usr/local/lib/pulp
#     owner: pulp
#     group: pulp
#     recurse: true

# - name: Verify Pulp Python dependencies
#   ansible.builtin.command:
#     cmd: /usr/local/lib/pulp/bin/python -m pip check
#   register: repo_pulp_pip_check
#   changed_when: false
#   failed_when: repo_pulp_pip_check.rc != 0
