---
- name: Show Pulp proxy environment
  ansible.builtin.command:
    cmd: env
  register: repo_pulp_env
  changed_when: false

- name: Display Pulp proxy environment
  ansible.builtin.debug:
    msg: "{{ repo_pulp_env.stdout_lines | select('match', '(?i).*proxy.*') | list }}"

- name: Install and configure Pulp
  ansible.builtin.include_role:
    name: pulp.pulp_installer.pulp_all_services

  vars:
    pulp_install_plugins:
      pulp-rpm:
        version: "3.19.11"
      pulp-deb:
        version: "2.20.2"

    # pulp_version: "3.32.3"
    # pulp_dependencies_upgrade: true

    pulp_media_root: "{{ repo_storage_path }}/media"

    pulp_settings:
      secret_key: "{{ vault_pulp_secret_key }}"
      content_origin: "{{ repo_pulp_content_origin }}"

    pulp_default_admin_password: "{{ vault_pulp_admin_password }}"

    pulp_workers: "{{ repo_workers }}"

    pulp_python_interpreter: "/usr/bin/python3.11"
