---
- name: Check Rocky BaseOS repository
  ansible.builtin.uri:
    url: "{{ repo_nexus_api_url }}/service/rest/v1/repositories/yum/proxy/{{ repo_nexus_rocky_baseos.name }}"
    method: GET
    user: "{{ repo_nexus_admin_user }}"
    password: "{{ repo_nexus_admin_password }}"
    force_basic_auth: true
    status_code:
      - 200
      - 404
  register: repo_nexus_rocky_baseos_check
  when: repo_nexus_rocky_enabled | bool
  no_log: true

- name: Create Rocky BaseOS repository
  ansible.builtin.uri:
    url: "{{ repo_nexus_api_url }}/service/rest/v1/repositories/yum/proxy"
    method: POST
    user: "{{ repo_nexus_admin_user }}"
    password: "{{ repo_nexus_admin_password }}"
    force_basic_auth: true
    body_format: json
    body:
      name: "{{ repo_nexus_rocky_baseos.name }}"
      online: true
      storage:
        blobStoreName: default
        strictContentTypeValidation: true
      proxy:
        remoteUrl: "{{ repo_nexus_rocky_baseos.url }}"
        contentMaxAge: 1440
        metadataMaxAge: 60
      negativeCache:
        enabled: true
        timeToLive: 1440
      httpClient:
        blocked: false
        autoBlock: true
    status_code: 201
  when:
    - repo_nexus_rocky_enabled | bool
    - repo_nexus_rocky_baseos_check.status == 404
  no_log: true

- name: Check EPEL repository
  ansible.builtin.uri:
    url: "{{ repo_nexus_api_url }}/service/rest/v1/repositories/yum/proxy/{{ repo_nexus_epel.name }}"
    method: GET
    user: "{{ repo_nexus_admin_user }}"
    password: "{{ repo_nexus_admin_password }}"
    force_basic_auth: true
    status_code:
      - 200
      - 404
  register: repo_nexus_epel_check
  when: repo_nexus_epel_enabled | bool
  no_log: true

- name: Create EPEL repository
  ansible.builtin.uri:
    url: "{{ repo_nexus_api_url }}/service/rest/v1/repositories/yum/proxy"
    method: POST
    user: "{{ repo_nexus_admin_user }}"
    password: "{{ repo_nexus_admin_password }}"
    force_basic_auth: true
    body_format: json
    body:
      name: "{{ repo_nexus_epel.name }}"
      online: true
      storage:
        blobStoreName: default
        strictContentTypeValidation: true
      proxy:
        remoteUrl: "{{ repo_nexus_epel.url }}"
        contentMaxAge: 1440
        metadataMaxAge: 60
      negativeCache:
        enabled: true
        timeToLive: 1440
      httpClient:
        blocked: false
        autoBlock: true
    status_code: 201
  when:
    - repo_nexus_epel_enabled | bool
    - repo_nexus_epel_check.status == 404
  no_log: true

- name: Check Debian repository
  ansible.builtin.uri:
    url: "{{ repo_nexus_api_url }}/service/rest/v1/repositories/apt/proxy/{{ repo_nexus_debian.name }}"
    method: GET
    user: "{{ repo_nexus_admin_user }}"
    password: "{{ repo_nexus_admin_password }}"
    force_basic_auth: true
    status_code:
      - 200
      - 404
  register: repo_nexus_debian_check
  when: repo_nexus_debian_enabled | bool
  no_log: true

- name: Create Debian repository
  ansible.builtin.uri:
    url: "{{ repo_nexus_api_url }}/service/rest/v1/repositories/apt/proxy"
    method: POST
    user: "{{ repo_nexus_admin_user }}"
    password: "{{ repo_nexus_admin_password }}"
    force_basic_auth: true
    body_format: json
    body:
      name: "{{ repo_nexus_debian.name }}"
      online: true

      storage:
        blobStoreName: default
        strictContentTypeValidation: true

      proxy:
        remoteUrl: "{{ repo_nexus_debian.url }}"
        contentMaxAge: 1440
        metadataMaxAge: 60

      negativeCache:
        enabled: true
        timeToLive: 1440

      httpClient:
        blocked: false
        autoBlock: true

      apt:
        distribution: "{{ repo_nexus_debian.distribution }}"
        flat: "{{ repo_nexus_debian.flat }}"
        enforceDistribution: "{{ repo_nexus_debian.enforce_distribution }}"

    status_code: 201
  when:
    - repo_nexus_debian_enabled | bool
    - repo_nexus_debian_check.status == 404
  no_log: true

- name: Check Debian Security repository
  ansible.builtin.uri:
    url: "{{ repo_nexus_api_url }}/service/rest/v1/repositories/apt/proxy/{{ repo_nexus_debian_security.name }}"
    method: GET
    user: "{{ repo_nexus_admin_user }}"
    password: "{{ repo_nexus_admin_password }}"
    force_basic_auth: true
    status_code:
      - 200
      - 404
  register: repo_nexus_debian_security_check
  when: repo_nexus_debian_enabled | bool
  no_log: true

- name: Create Debian Security repository
  ansible.builtin.uri:
    url: "{{ repo_nexus_api_url }}/service/rest/v1/repositories/apt/proxy"
    method: POST
    user: "{{ repo_nexus_admin_user }}"
    password: "{{ repo_nexus_admin_password }}"
    force_basic_auth: true
    body_format: json
    body:
      name: "{{ repo_nexus_debian_security.name }}"
      online: true

      storage:
        blobStoreName: default
        strictContentTypeValidation: true

      proxy:
        remoteUrl: "{{ repo_nexus_debian_security.url }}"
        contentMaxAge: 1440
        metadataMaxAge: 60

      negativeCache:
        enabled: true
        timeToLive: 1440

      httpClient:
        blocked: false
        autoBlock: true

      apt:
        distribution: "{{ repo_nexus_debian_security.distribution }}"
        flat: "{{ repo_nexus_debian_security.flat }}"
        enforceDistribution: "{{ repo_nexus_debian_security.enforce_distribution }}"

    status_code: 201
  when:
    - repo_nexus_debian_enabled | bool
    - repo_nexus_debian_security_check.status == 404
  no_log: true
