---
- name: Check Docker proxy repositories
  ansible.builtin.uri:
    url: "{{ repo_nexus_api_url }}/service/rest/v1/repositories/docker/proxy/{{ item.name }}"
    method: GET
    user: "{{ repo_nexus_admin_user }}"
    password: "{{ repo_nexus_admin_password }}"
    force_basic_auth: true
    status_code:
      - 200
      - 404
    validate_certs: false
  loop: "{{ repo_nexus_docker_proxies }}"
  register: repo_nexus_docker_checks
  when: repo_nexus_docker_enabled | bool
  #no_log: true

# -----------------------------------------------------------------------------
# Rocky Linux 9 - BaseOS
# -----------------------------------------------------------------------------

- name: Check Rocky BaseOS repository
  ansible.builtin.uri:
    url: "{{ repo_nexus_api_url }}/service/rest/v1/repositories/yum/proxy/{{ repo_nexus_rocky_baseos.name }}"
    method: GET
    user: "{{ repo_nexus_admin_user }}"
    password: "{{ repo_nexus_admin_password }}"
    force_basic_auth: true
    status_code:
      - 200
      - 404
    validate_certs: false
  register: repo_nexus_rocky_baseos_check
  when: repo_nexus_rocky_enabled | bool
  no_log: true

- name: Create Rocky BaseOS repository
  ansible.builtin.uri:
    url: "{{ repo_nexus_api_url }}/service/rest/v1/repositories/yum/proxy"
    method: POST
    user: "{{ repo_nexus_admin_user }}"
    password: "{{ repo_nexus_admin_password }}"
    force_basic_auth: true
    headers:
      Content-Type: application/json
    body_format: json
    body:
      name: "{{ repo_nexus_rocky_baseos.name }}"
      online: true

      storage:
        blobStoreName: default
        strictContentTypeValidation: true

      proxy:
        remoteUrl: "{{ repo_nexus_rocky_baseos.url }}"
        contentMaxAge: 1440
        metadataMaxAge: 60

      negativeCache:
        enabled: true
        timeToLive: 1440

      httpClient:
        blocked: false
        autoBlock: true
        connection:
          retries: 3
          timeout: 60

    status_code: 201
    validate_certs: false
  when:
    - repo_nexus_rocky_enabled | bool
    - repo_nexus_rocky_baseos_check.status == 404

# -----------------------------------------------------------------------------
# Rocky Linux 9 - AppStream
# -----------------------------------------------------------------------------

- name: Check Rocky AppStream repository
  ansible.builtin.uri:
    url: "{{ repo_nexus_api_url }}/service/rest/v1/repositories/yum/proxy/{{ repo_nexus_rocky_appstream.name }}"
    method: GET
    user: "{{ repo_nexus_admin_user }}"
    password: "{{ repo_nexus_admin_password }}"
    force_basic_auth: true
    status_code:
      - 200
      - 404
    validate_certs: false
  register: repo_nexus_rocky_appstream_check
  when: repo_nexus_rocky_enabled | bool
  no_log: true

- name: Create Rocky AppStream repository
  ansible.builtin.uri:
    url: "{{ repo_nexus_api_url }}/service/rest/v1/repositories/yum/proxy"
    method: POST
    user: "{{ repo_nexus_admin_user }}"
    password: "{{ repo_nexus_admin_password }}"
    force_basic_auth: true
    headers:
      Content-Type: application/json
    body_format: json
    body:
      name: "{{ repo_nexus_rocky_appstream.name }}"
      online: true

      storage:
        blobStoreName: default
        strictContentTypeValidation: true

      proxy:
        remoteUrl: "{{ repo_nexus_rocky_appstream.url }}"
        contentMaxAge: 1440
        metadataMaxAge: 60

      negativeCache:
        enabled: true
        timeToLive: 1440

      httpClient:
        blocked: false
        autoBlock: true
        connection:
          retries: 3
          timeout: 60

    status_code: 201
    validate_certs: false
  when:
    - repo_nexus_rocky_enabled | bool
    - repo_nexus_rocky_appstream_check.status == 404
  no_log: true

# -----------------------------------------------------------------------------
# EPEL 9
# -----------------------------------------------------------------------------

- name: Check EPEL repository
  ansible.builtin.uri:
    url: "{{ repo_nexus_api_url }}/service/rest/v1/repositories/yum/proxy/{{ repo_nexus_epel.name }}"
    method: GET
    user: "{{ repo_nexus_admin_user }}"
    password: "{{ repo_nexus_admin_password }}"
    force_basic_auth: true
    status_code:
      - 200
      - 404
    validate_certs: false
  register: repo_nexus_epel_check
  when: repo_nexus_epel_enabled | bool
  no_log: true

- name: Create EPEL repository
  ansible.builtin.uri:
    url: "{{ repo_nexus_api_url }}/service/rest/v1/repositories/yum/proxy"
    method: POST
    user: "{{ repo_nexus_admin_user }}"
    password: "{{ repo_nexus_admin_password }}"
    force_basic_auth: true
    headers:
      Content-Type: application/json
    body_format: json
    body:
      name: "{{ repo_nexus_epel.name }}"
      online: true

      storage:
        blobStoreName: default
        strictContentTypeValidation: true

      proxy:
        remoteUrl: "{{ repo_nexus_epel.url }}"
        contentMaxAge: 1440
        metadataMaxAge: 60

      negativeCache:
        enabled: true
        timeToLive: 1440

      httpClient:
        blocked: false
        autoBlock: true
        connection:
          retries: 3
          timeout: 60

    status_code: 201
    validate_certs: false
  when:
    - repo_nexus_epel_enabled | bool
    - repo_nexus_epel_check.status == 404
  no_log: true

# -----------------------------------------------------------------------------
# Debian 12
# -----------------------------------------------------------------------------

- name: Check Debian repository
  ansible.builtin.uri:
    url: "{{ repo_nexus_api_url }}/service/rest/v1/repositories/apt/proxy/{{ repo_nexus_debian.name }}"
    method: GET
    user: "{{ repo_nexus_admin_user }}"
    password: "{{ repo_nexus_admin_password }}"
    force_basic_auth: true
    status_code:
      - 200
      - 404
    validate_certs: false
  register: repo_nexus_debian_check
  when: repo_nexus_debian_enabled | bool
  no_log: true

- name: Create Debian repository
  ansible.builtin.uri:
    url: "{{ repo_nexus_api_url }}/service/rest/v1/repositories/apt/proxy"
    method: POST
    user: "{{ repo_nexus_admin_user }}"
    password: "{{ repo_nexus_admin_password }}"
    force_basic_auth: true
    headers:
      Content-Type: application/json
    body_format: json
    body:
      name: "{{ repo_nexus_debian.name }}"
      online: true

      storage:
        blobStoreName: default
        strictContentTypeValidation: true

      proxy:
        remoteUrl: "{{ repo_nexus_debian.url }}"
        contentMaxAge: 1440
        metadataMaxAge: 60

      negativeCache:
        enabled: true
        timeToLive: 1440

      httpClient:
        blocked: false
        autoBlock: true
        connection:
          retries: 3
          timeout: 60

      apt:
        distribution: "{{ repo_nexus_debian.distribution }}"
        flat: "{{ repo_nexus_debian.flat }}"
        enforceDistribution: "{{ repo_nexus_debian.enforce_distribution }}"

    status_code: 201
    validate_certs: false
  when:
    - repo_nexus_debian_enabled | bool
    - repo_nexus_debian_check.status == 404

# -----------------------------------------------------------------------------
# Debian 12 Security
# -----------------------------------------------------------------------------

- name: Check Debian Security repository
  ansible.builtin.uri:
    url: "{{ repo_nexus_api_url }}/service/rest/v1/repositories/apt/proxy/{{ repo_nexus_debian_security.name }}"
    method: GET
    user: "{{ repo_nexus_admin_user }}"
    password: "{{ repo_nexus_admin_password }}"
    force_basic_auth: true
    status_code:
      - 200
      - 404
    validate_certs: false
  register: repo_nexus_debian_security_check
  when: repo_nexus_debian_enabled | bool
  no_log: true

- name: Create Debian Security repository
  ansible.builtin.uri:
    url: "{{ repo_nexus_api_url }}/service/rest/v1/repositories/apt/proxy"
    method: POST
    user: "{{ repo_nexus_admin_user }}"
    password: "{{ repo_nexus_admin_password }}"
    force_basic_auth: true
    headers:
      Content-Type: application/json
    body_format: json
    body:
      name: "{{ repo_nexus_debian_security.name }}"
      online: true

      storage:
        blobStoreName: default
        strictContentTypeValidation: true

      proxy:
        remoteUrl: "{{ repo_nexus_debian_security.url }}"
        contentMaxAge: 1440
        metadataMaxAge: 60

      negativeCache:
        enabled: true
        timeToLive: 1440

      httpClient:
        blocked: false
        autoBlock: true
        connection:
          retries: 3
          timeout: 60

      apt:
        distribution: "{{ repo_nexus_debian_security.distribution }}"
        flat: "{{ repo_nexus_debian_security.flat }}"
        enforceDistribution: "{{ repo_nexus_debian_security.enforce_distribution }}"

    status_code: 201
    validate_certs: false
  when:
    - repo_nexus_debian_enabled | bool
    - repo_nexus_debian_security_check.status == 404
  no_log: true

#----
# Docker repo
#----

- name: Check Docker repositories
  ansible.builtin.uri:
    url: "{{ repo_nexus_api_url }}/service/rest/v1/repositories/docker/proxy/{{ item.name }}"
    method: GET
    user: "{{ repo_nexus_admin_user }}"
    password: "{{ repo_nexus_admin_password }}"
    force_basic_auth: true
    status_code:
      - 200
      - 404
    validate_certs: false
  register: repo_nexus_docker_checks
  loop: "{{ repo_nexus_docker_proxies }}"
  when: repo_nexus_docker_enabled | bool
  no_log: true

- name: Create Docker Proxy repository
  ansible.builtin.uri:
    url: "{{ repo_nexus_api_url }}/service/rest/v1/repositories/docker/proxy"
    method: POST
    user: "{{ repo_nexus_admin_user }}"
    password: "{{ repo_nexus_admin_password }}"
    force_basic_auth: true
    headers:
      Content-Type: application/json
    body_format: json
    body:
      name: "{{ repo_nexus_docker_proxy.name }}"
      online: true

      storage:
        blobStoreName: default
        strictContentTypeValidation: true

      proxy:
        remoteUrl: "{{ item.item.url }}"
        contentMaxAge: 1440
        metadataMaxAge: 1440

      negativeCache:
        enabled: true
        timeToLive: 1440

      httpClient:
        blocked: false
        autoBlock: true
        connection:
          retries: 3
          timeout: 60

      dockerProxy:
        indexType: "HUB"

      docker:
        v1Enabled: false
        forceBasicAuth: false
        httpPort: 8082
    status_code: 201
    validate_certs: false
  loop: "{{ repo_nexus_docker_checks.results }}"
  loop_control:
    label: "{{ item.item.name }}"
  when:
    - repo_nexus_docker_enabled | bool
    - item.status == 404
  #no_log: true

- name: Configure Nexus anonymous access
  ansible.builtin.uri:
    url: "{{ repo_nexus_api_url }}/service/rest/v1/security/anonymous"
    method: PUT
    user: "{{ repo_nexus_admin_user }}"
    password: "{{ repo_nexus_admin_password }}"
    force_basic_auth: true
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      enabled: "{{ repo_nexus_anonymous_access_enabled }}"
    status_code:
      - 200
      - 204
    validate_certs: false
  no_log: true

- name: Configure Docker insecure registries
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0644"
    content: |
      {
        "insecure-registries": [
          "{{ repo_fqdn }}:8082",
          "127.0.0.1:8082"
        ]
      }
  notify: Restart Docker

- name: Wait for Nexus to completely start up and open ports
  ansible.builtin.wait_for:
    host: "127.0.0.1"
    port: 8082
    delay: 5
    timeout: 120
    state: started

- name: Get current active security realms
  ansible.builtin.uri:
    url: "{{ repo_nexus_api_url }}/service/rest/v1/security/realms/active"
    method: GET
    user: "{{ repo_nexus_admin_user }}"
    password: "{{ repo_nexus_admin_password }}"
    force_basic_auth: true
    validate_certs: false
    status_code: 200
  register: current_nexus_realms
  no_log: true

- name: Debug current active realms
  ansible.builtin.debug:
    msg: "Current active realms: {{ current_nexus_realms.json }}"

- name: Activate Docker Bearer Token Realm
  ansible.builtin.uri:
    url: "{{ repo_nexus_api_url }}/service/rest/v1/security/realms/active"
    method: PUT
    user: "{{ repo_nexus_admin_user }}"
    password: "{{ repo_nexus_admin_password }}"
    force_basic_auth: true
    headers:
      Content-Type: "application/json"
    body_format: raw
    body: >-
      {{
        (
          current_nexus_realms.json
          | default([])
          | union(['DockerToken'])
        )
        | to_json
      }}
    status_code: 204
    validate_certs: false
  no_log: true

- name: Verify Docker proxy repositories
  ansible.builtin.uri:
    url: "{{ repo_nexus_api_url }}/service/rest/v1/repositories/docker/proxy/{{ item.name }}"
    method: GET
    user: "{{ repo_nexus_admin_user }}"
    password: "{{ repo_nexus_admin_password }}"
    force_basic_auth: true
    status_code: 200
    validate_certs: false
  loop: "{{ repo_nexus_docker_proxies }}"
  when: repo_nexus_docker_enabled | bool
  no_log: true
