---
- name: Check Rocky Linux RPM repository
  ansible.builtin.uri:
    url: "{{ repo_pulp_api_url }}/repositories/rpm/rpm/?name={{ repo_rocky_name | urlencode }}"
    method: GET
    user: "{{ repo_pulp_api_user }}"
    password: "{{ repo_pulp_api_password }}"
    force_basic_auth: true
    validate_certs: false
    status_code: 200
    return_content: true
  register: repo_rocky_repository_lookup
  changed_when: false

- name: Create Rocky Linux RPM repository
  ansible.builtin.uri:
    url: "{{ repo_pulp_api_url }}/repositories/rpm/rpm/"
    method: POST
    user: "{{ repo_pulp_api_user }}"
    password: "{{ repo_pulp_api_password }}"
    force_basic_auth: true
    body_format: json
    body:
      name: "{{ repo_rocky_name }}"
    status_code:
      - 201
      - 202
    validate_certs: false
  register: repo_rocky_repository_create
  when: repo_rocky_repository_lookup.json.count == 0

- name: Set Rocky Linux repository href
  ansible.builtin.set_fact:
    repo_rocky_repository_href: >-
      {{
        repo_rocky_repository_create.json.pulp_href
        if repo_rocky_repository_lookup.json.count == 0
        else repo_rocky_repository_lookup.json.results[0].pulp_href
      }}

- name: Check Rocky Linux RPM remote
  ansible.builtin.uri:
    url: "{{ repo_pulp_api_url }}/remotes/rpm/rpm/?name={{ repo_rocky_name | urlencode }}"
    method: GET
    user: "{{ repo_pulp_api_user }}"
    password: "{{ repo_pulp_api_password }}"
    force_basic_auth: true
    validate_certs: false
    status_code: 200
    return_content: true
  register: repo_rocky_remote_lookup
  changed_when: false

- name: Create Rocky Linux RPM remote
  ansible.builtin.uri:
    url: "{{ repo_pulp_api_url }}/remotes/rpm/rpm/"
    method: POST
    user: "{{ repo_pulp_api_user }}"
    password: "{{ repo_pulp_api_password }}"
    force_basic_auth: true
    body_format: json
    body:
      name: "{{ repo_rocky_name }}"
      url: "{{ repo_rocky_remote_url }}"
    status_code:
      - 201
      - 202
    validate_certs: false
  register: repo_rocky_remote_create
  when: repo_rocky_remote_lookup.json.count == 0

- name: Set Rocky Linux remote href
  ansible.builtin.set_fact:
    repo_rocky_remote_href: >-
      {{
        repo_rocky_remote_create.json.pulp_href
        if repo_rocky_remote_lookup.json.count == 0
        else repo_rocky_remote_lookup.json.results[0].pulp_href
      }}

- name: Sync Rocky Linux repository
  ansible.builtin.uri:
    url: "{{  repo_pulp_base_url }}{{ repo_rocky_remote_href }}sync/"
    method: POST
    user: "{{ repo_pulp_api_user }}"
    password: "{{ repo_pulp_api_password }}"
    force_basic_auth: true
    body_format: json
    body:
      repository: "{{ repo_rocky_repository_href }}"
    status_code:
      - 202
    validate_certs: false
  register: repo_rocky_sync
