---
- name: Configuration etcd cluster
  become: true
  block:
    - name: Run etcd prerequisites
      ansible.builtin.include_tasks:
        file: prerequisites.yml

    - name: Create directories
      ansible.builtin.include_tasks:
        file: directories.yml

    - name: Configure firewall
      ansible.builtin.include_tasks:
        file: firewall.yml

    - name: Install etcd
      ansible.builtin.include_tasks:
        file: install.yml

    - name: Configure TLS
      ansible.builtin.include_tasks:
        file: tls.yml

    - name: Configure etcd
      ansible.builtin.include_tasks:
        file: config.yml

    - name: Configure systemd
      ansible.builtin.include_tasks:
        file: systemd.yml

    - name: Validate etcd
      ansible.builtin.include_tasks:
        file: validate.yml
