---
# ==========================================================
# Cilium BGP topology
# ==========================================================

kubernetes_bgp_as: 65100

vyos_bgp_as: 65000

kubernetes_bgp_peers:
  - name: vyos-router-01
    address: "10.50.30.1"
    as: 65000

  - name: vyos-router-02
    address: "10.50.30.2"
    as: 65000
