- name: Configure VRRP
  vyos.vyos.vyos_config:
    lines: |
      {% for item in vgt_vlans %}
      set high-availability vrrp group VLAN{{ item.id }} interface eth1.{{ item.id }}
      set high-availability vrrp group VLAN{{ item.id }} vrid {{ item.id }}
      set high-availability vrrp group VLAN{{ item.id }} priority {{ router_priority }}
      set high-availability vrrp group VLAN{{ item.id }} address {{ item.subnet }}.254/24
      set high-availability vrrp group VLAN{{ item.id }} hello-source-address {{ item.subnet }}.{{ ip_suffix }}
      set high-availability vrrp group VLAN{{ item.id }} preempt
      {% endfor %}
    match: none

- name: Save configuration
  vyos.vyos.vyos_config:
    save: true
