---
- name: Gather VRRP configuration
  vyos.vyos.vyos_command:
    commands:
      - show configuration commands | match "high-availability vrrp group {{ external_ntp.group }}"
  register: ntp_vrrp_config

- name: Configure External NTP VRRP
  vyos.vyos.vyos_config:
    lines:
      - "set high-availability vrrp group {{ external_ntp.group }} interface {{ external_ntp.interface }}.{{ external_ntp.vlan_id }}"
      - "set high-availability vrrp group {{ external_ntp.group }} vrid {{ external_ntp.vrrp.vrid }}"
      - "set high-availability vrrp group {{ external_ntp.group }} priority {{ router_priority }}"
      - "set high-availability vrrp group {{ external_ntp.group }} address '{{ external_ntp.addresses.vip }}/24'"
      - >-
        {% if router_priority | int > 100 %}
        set high-availability vrrp group {{ external_ntp.group }} preempt-delay 30
        {% else %}
        set high-availability vrrp group {{ external_ntp.group }} no-preempt
        {% endif %}
  when: external_ntp.addresses.vip not in ntp_vrrp_config.stdout[0]
