---
- name: Gather NTP configuration
  vyos.vyos.vyos_command:
    commands:
      - show configuration commands | match "service ntp"
  register: ntp_service_config

- name: Configure External NTP service
  vyos.vyos.vyos_config:
    lines: |
      {% for server in external_ntp.forwarding.upstream_servers %}
      set service ntp server {{ server }}
      {% endfor %}

      set service ntp listen-address {{ external_ntp.addresses.vip }}

      {% for subnet in external_ntp.forwarding.allow_from %}
      set service ntp allow-client address {{ subnet }}
      {% endfor %}
  when: external_ntp.addresses.vip not in ntp_service_config.stdout[0]
  register: ntp_service
