---
- name: Configure External NTP VRRP
  vyos.vyos.vyos_config:
    parents:
      - high-availability vrrp group {{ external_ntp.group }}
    lines:
      - "interface {{ external_ntp.interface }}.{{ external_ntp.vlan_id }}"
      - "vrid {{ external_ntp.vrrp.vrid }}"
      - "priority {{ router_priority }}"
      - "address '{{ external_ntp.addresses.vip }}/24'"

      - >-
        {% if router_priority | int > 100 %}
        preempt-delay 30
        {% else %}
        no-preempt
        {% endif %}
