---
- name: Validate Vault HA configuration
  ansible.builtin.include_tasks:
    file: validate.yml

- name: Configure Vault VRRP
  ansible.builtin.include_tasks:
    file: vrrp.yml

- name: Configure Vault HA proxy
  ansible.builtin.include_tasks:
    file: haproxy.yml

- name: Commit Vault service configuration
  ansible.builtin.include_tasks:
    file: commit.yml
