---
- name: Kubernetes | Configure Debian firewall
  ansible.builtin.include_tasks: firewall_debian.yml
  when: ansible_os_family == "Debian"

- name: Kubernetes | Configure RedHat firewall
  ansible.builtin.include_tasks: firewall_redhat.yml
  when: ansible_os_family == "RedHat"
