---
- name: Kubernetes | Install Kubernetes packages on Debian
  ansible.builtin.include_tasks: kube_packages_debian.yml
  when: ansible_os_family == "Debian"

- name: Kubernetes | Install Kubernetes packages on RedHat
  ansible.builtin.include_tasks: kube_packages_redhat.yml
  when: ansible_os_family == "RedHat"
