---
- name: Configure DNS forwarding
  vyos.vyos.vyos_config:
    lines: |
      set service dns forwarding listen-address {{ external_dns.vrrp.vip }}
      set service dns forwarding cache-size {{ external_dns.cache_size }}

      {% for subnet in external_dns.allow_from %}
      set service dns forwarding allow-from {{ subnet }}
      {% endfor %}

      {% for dns in external_dns.forwarders %}
      set service dns forwarding name-server {{ dns }}
      {% endfor %}

    match: none

- name: Save configuration
  vyos.vyos.vyos_config:
    save: true
