---
- name: Configure descriptions on Trunk sub-interfaces (eth1)
  vyos.vyos.vyos_interfaces:
    config:
      - name: eth1
        vifs: "{{ trunk_interfaces }}"
    state: merged
  vars:
    trunk_interfaces: |
      {% set result = [] %}
      {% for vlan in vgt_vlans %}
      {% set _ = result.append({
        'vlan_id': vlan.id | int,
        'description': vlan.name,
        'enabled': true
      }) %}
      {% endfor %}
      {{ result }}

- name: Assign L3 IPv4 Gateways to Trunk sub-interfaces (eth1)
  vyos.vyos.vyos_l3_interfaces:
    config:
      - name: eth1
        vifs: "{{ trunk_l3_interfaces }}"
    state: merged
  vars:
    trunk_l3_interfaces: |
      {% set result = [] %}
      {% for vlan in vgt_vlans %}
      {% set _ = result.append({
        'vlan_id': vlan.id | int,
        'ipv4': [
          {
            'address': vlan.ip
          }
        ]
      }) %}
      {% endfor %}
      {{ result }}

- name: Commit and save configuration to boot.config
  vyos.vyos.vyos_config:
    save: true

- name: Gather applied L3 configuration for verification
  vyos.vyos.vyos_l3_interfaces:
    state: gathered
  register: current_l3_interfaces

- name: Build compact interfaces list
  ansible.builtin.set_fact:
    compact_interfaces_list: |
      {% set output = [] %}
      {% for interface in current_l3_interfaces.gathered %}
        {% if interface.vifs is defined %}
          {% for vif in interface.vifs %}
            {% set _ = output.append(interface.name ~ '.' ~ vif.vlan_id ~ ' -> ' ~ vif.ipv4[0].address) %}
          {% endfor %}
        {% endif %}
        {% if interface.ipv4 is defined %}
          {% for ip in interface.ipv4 %}
            {% set _ = output.append(interface.name ~ ' -> ' ~ ip.address) %}
          {% endfor %}
        {% endif %}
      {% endfor %}
      {{ output | sort | to_yaml }}

- name: Display running L3 interfaces configuration (Line by Line)
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ compact_interfaces_list | from_yaml }}"
  loop_control:
    label: "{{ item }}"
