---
haproxy_package: "haproxy"
keepalived_package: "keepalived"

haproxy_service: "haproxy"
keepalived_service: "keepalived"

haproxy_config_file: "/etc/haproxy/haproxy.cfg"
keepalived_config_file: "/etc/keepalived/keepalived.conf"
