---
- name: Gather HAProxy configuration
  vyos.vyos.vyos_command:
    commands:
      - show configuration commands | match "load-balancing haproxy"
  register: proxy_config

- name: Allow HAProxy to bind to VIP on backup node
  vyos.vyos.vyos_config:
    lines:
      - "set system sysctl parameter net.ipv4.ip_nonlocal_bind value 1"

- name: Configure HAProxy
  vyos.vyos.vyos_config:
    lines:
      # Backend
      - "set load-balancing haproxy backend proxy-backend mode tcp"
      - "set load-balancing haproxy backend proxy-backend balance round-robin"
      - "set load-balancing haproxy backend proxy-backend server proxy01 address {{ external_proxy.forwarding.upstream_server }}"
      - "set load-balancing haproxy backend proxy-backend server proxy01 port {{ external_proxy.forwarding.upstream_port }}"
      - "set load-balancing haproxy backend proxy-backend server proxy01 check"

      # Service
      - "set load-balancing haproxy service proxy-service mode tcp"
      - "set load-balancing haproxy service proxy-service listen-address {{ external_proxy.addresses.vip }}"
      - "set load-balancing haproxy service proxy-service port {{ external_proxy.forwarding.upstream_port }}"
      - "set load-balancing haproxy service proxy-service backend proxy-backend"

  register: proxy_service
