---
- name: Gather Proxy VRRP configuration
  vyos.vyos.vyos_command:
    commands:
      - 'show configuration commands | match "high-availability vrrp group {{ external_proxy.group }}"'
  register: proxy_vrrp_config

- name: Configure Global VRRP Engine Parameters
  vyos.vyos.vyos_config:
    lines:
      - "set high-availability vrrp global-parameters garp master-delay 1"
      - "set high-availability vrrp global-parameters garp master-repeat 5"

- name: Configure External Proxy VRRP Group
  vars:
    preempt_cmd: >-
      {{
        'set high-availability vrrp group ' ~ external_proxy.group ~ ' preempt-delay 30'
        if router_priority | int > 100
        else
        'set high-availability vrrp group ' ~ external_proxy.group ~ ' no-preempt'
      }}

  vyos.vyos.vyos_config:
    lines:
      - "set high-availability vrrp group {{ external_proxy.group }} interface {{ external_proxy.interface }}.{{ external_proxy.vlan_id }}"
      - "set high-availability vrrp group {{ external_proxy.group }} vrid {{ external_proxy.vrrp.vrid }}"
      - "set high-availability vrrp group {{ external_proxy.group }} priority {{ router_priority }}"
      - "set high-availability vrrp group {{ external_proxy.group }} address {{ external_proxy.addresses.vip }}/24"
      - "{{ preempt_cmd }}"

      # Clear out any stale validation errors
      - "delete high-availability vrrp group {{ external_proxy.group }} health-check"
      - "delete high-availability vrrp group {{ external_proxy.group }} rfc3768-compatibility"
      - "delete high-availability vrrp group {{ external_proxy.group }} track"

      # Map directly to ClusterSync group
      - "set high-availability vrrp sync-group ClusterSync member {{ external_proxy.group }}"

      # Group level health checks
      - "set high-availability vrrp sync-group ClusterSync health-check script '/bin/ping -c 2 -W 1 {{ external_proxy.forwarding.upstream_server }}'"
      - "set high-availability vrrp sync-group ClusterSync health-check interval 2"
      - "set high-availability vrrp sync-group ClusterSync health-check failure-count 2"
  when: >
    proxy_vrrp_config.stdout is defined and
    (proxy_vrrp_config.stdout | length > 0) and
    (external_proxy.addresses.vip not in (proxy_vrrp_config.stdout | first))
  register: proxy_vrrp
