---
- name: Configure DHCP pools
  vyos.vyos.vyos_config:
    lines:
      - "set service dhcp-server shared-network-name VLAN{{ item.id }} subnet {{ item.network }} default-router '{{ item.gateway }}'"
      - "set service dhcp-server shared-network-name VLAN{{ item.id }} subnet {{ item.network }} lease '{{ item.dhcp.lease }}'"
      - "set service dhcp-server shared-network-name VLAN{{ item.id }} subnet {{ item.network }} range 0 start '{{ item.subnet }}.{{ item.dhcp.range.start }}'"
      - "set service dhcp-server shared-network-name VLAN{{ item.id }} subnet {{ item.network }} range 0 stop '{{ item.subnet }}.{{ item.dhcp.range.stop }}'"

  loop: "{{ vgt_vlans }}"
  when:
    - item.dhcp is defined
    - item.dhcp.enabled
