---
- name: Create Vault configuration directory
  ansible.builtin.file:
    path: "{{ vault_config_dir }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0750"

- name: Create Vault data directory
  ansible.builtin.file:
    path: "{{ vault_data_dir }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0750"

- name: Deploy Vault configuration
  ansible.builtin.template:
    src: vault.hcl.j2
    dest: "{{ vault_config_dir }}/vault.hcl"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0640"
  notify: Restart Vault

- name: Enable and start Vault
  ansible.builtin.systemd:
    name: vault
    enabled: true
    state: started
    daemon_reload: true

- name: Configure Vault CLI environment
  ansible.builtin.copy:
    dest: "/home/ansible/.vault_env"
    content: |
      export VAULT_ADDR="https://{{ vault_fqdn }}:{{ vault_api_port }}"
      export VAULT_CACERT="{{ vault_tls_ca_cert }}"
    owner: ansible
    group: ansible
    mode: "0640"

- name: Configure Vault CLI environment in bash profile
  ansible.builtin.lineinfile:
    path: "/home/ansible/.bash_profile"
    line: "source /home/ansible/.vault_env"
    state: present
    create: true
    owner: ansible
    group: ansible
    mode: "0640"
