---
- name: Allow Vault API from Vault cluster
  ansible.posix.firewalld:
    rich_rule: >-
      rule family="ipv4"
      source address="{{ hostvars[item].ansible_host }}"
      port port="{{ vault_api_port }}"
      protocol="tcp"
      accept
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ groups['vault_cluster'] }}"
  when: item != inventory_hostname

- name: Allow Vault cluster communication from Vault cluster
  ansible.posix.firewalld:
    rich_rule: >-
      rule family="ipv4"
      source address="{{ hostvars[item].ansible_host }}"
      port port="{{ vault_cluster_port }}"
      protocol="tcp"
      accept
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ groups['vault_cluster'] }}"
  when: item != inventory_hostname

- name: Allow Vault API from management network
  ansible.posix.firewalld:
    rich_rule: >-
      rule family="ipv4"
      source address="{{ vault_management_network }}"
      port port="{{ vault_api_port }}"
      protocol="tcp"
      accept
    permanent: true
    immediate: true
    state: enabled

- name: Allow Vault API from VyOS routers
  ansible.posix.firewalld:
    rich_rule: >-
      rule family="ipv4"
      source address="{{ hostvars[item].vault_backend_source_ip }}"
      port port="{{ vault_api_port }}"
      protocol="tcp"
      accept
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ groups['vyos_routers'] }}"
  loop_control:
    label: "{{ item }} -> {{ hostvars[item].vault_backend_source_ip }}"
