---
- name: Allow Vault API from Vault cluster
  ansible.posix.firewalld:
    rich_rule: 'rule family="ipv4" source address="{{ hostvars[item].ansible_host }}" port port="8200" protocol="tcp" accept'
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ groups['vault_cluster'] }}"
  when: hostvars[item].inventory_hostname != inventory_hostname

- name: Allow Vault cluster communication from Vault cluster
  ansible.posix.firewalld:
    rich_rule: 'rule family="ipv4" source address="{{ hostvars[item].ansible_host }}" port port="8201" protocol="tcp" accept'
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ groups['vault_cluster'] }}"
  when: hostvars[item].inventory_hostname != inventory_hostname
