---
- name: Install Vault
  ansible.builtin.import_tasks: install.yml

- name: Configure Vault TLS
  ansible.builtin.import_tasks: tls.yml

- name: Configure Vault firewall
  ansible.builtin.import_tasks: firewall.yml

- name: Configure Vault
  ansible.builtin.import_tasks: configure.yml

- name: Bootstrap Vault cluster
  ansible.builtin.import_tasks: bootstrap.yml

- name: Validate Vault
  ansible.builtin.import_tasks: validate.yml
