- name: Create Vault TLS directory
  ansible.builtin.file:
    path: "{{ vault_tls_dir }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0750"

- name: Deploy Vault TLS certificate
  ansible.builtin.copy:
    src: "{{ vault_pki_dir }}/{{ inventory_hostname }}.crt"
    dest: "{{ vault_tls_cert_file }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0644"
  notify: Restart Vault

- name: Deploy Vault TLS private key
  ansible.builtin.copy:
    src: "{{ vault_pki_dir }}/{{ inventory_hostname }}.key"
    dest: "{{ vault_tls_key_file }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0600"
  notify: Restart Vault
