---
collections:
  - name: ansible.posix
  - name: community.general
  - name: community.crypto
  - name: pulp.pulp_installer

roles:
  - name: geerlingguy.postgresql

#ansible-galaxy collection install -r requirements.yml
#ansible-galaxy collection list | grep community.crypto
#ansible-galaxy collection install community.crypto
