---
- name: Configure External DNS service address
  vyos.vyos.vyos_config:
    lines:
      - >-
        set interfaces ethernet {{ external_dns.interface }}
        vif {{ external_dns.vlan_id }}
        address
        {{
          external_dns.addresses.primary
          if ip_suffix | int == 1
          else external_dns.addresses.secondary
        }}/24

    match: none
