---
- name: Configure common settings for Etcd cluster
  hosts: etcd
  become: true
  roles:
    - common
# - name: Configure etcd nodes
#   hosts: etcd
#   become: true
#   serial: 1
#   roles:
#     - etcd
