all:
  children:
    # Network Environment
    vyos_routers:
      hosts:
        vyos-01:
          ansible_host: 10.50.10.11
        vyos-02:
          ansible_host: 10.50.10.12

    #Repo Environment
    repositories:
      hosts:
        repo-01:
          ansible_host: 10.50.60.60

    # loadbalancers:
    #   hosts:
    #     lb-01:
    #       ansible_host:

    # control_plane:
    #   hosts:
    #     cp-01:
    #       ansible_host:

    # workers:
    #   hosts:
    #     worker-01:
    #       ansible_host:

    # kubernetes:
    #   children:
    #     control_plane:
    #     workers:

    # linux:
    #   children:
    #     repositories:
    #     loadbalancers:
    #     kubernetes:
